services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: base64:gwXOmynNupm1TUeuny5Qullr/iyM2BqZpVlgpRL4SxA=
      APP_URL: http://localhost:8000
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: mini_binance
      DB_USERNAME: mini_binance
      DB_PASSWORD: secret
      CACHE_STORE: redis
      REDIS_CLIENT: predis
      REDIS_HOST: redis
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: file
    volumes:
      - .:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started

  mysql:
    image: mysql:8.4
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mini_binance
      MYSQL_USER: mini_binance
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  mysql-data:
